# Generated by Django 5.2.10 on 2026-04-22 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_add_song_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Role in this service (e.g., Guitar, Drums, Keys)', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appearances', to='band.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='band.service')),
            ],
            options={
                'ordering': ['person__name'],
                'unique_together': {('service', 'person')},
            },
        ),
    ]
